language: php

php:
  - '7.1'
  - '7.2'

install:
    - travis_retry composer install --no-interaction --prefer-dist
    
before_script:
  - mkdir -p build/logs
  
script:
  - travis_wait ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls